### ISSUE TITLE
Video Uploader Component Styling

### ISSUE THREAD

**Issue by bwmelon97** [SGM-StyleTransfer/model-serve-frontend#2]
<img width="675" alt="image" src="https://user-images.githubusercontent.com/39655003/180134622-0883dfed-2c01-4ea3-b0cc-5f197b0db8ac.png">

현재 비디오 컴포넌트가 아무 영상이 선택되어 있지 않을 때, 빈 영역으로 인식되어 컴포넌트의 영역이 불분명하게 되어 있습니다.
비디오가 선택되어 있지 않을 때는 'video not selected' 라는 문구와 함께 비디오 영상이 나타나는 영역 만큼 차지되었으면 합니다.

**Comment by hellog2n** [comment]
매우 좋은 것 같습니다.

**Comment by bwmelon97** [comment]
![프로토타입 스케치-1](https://user-images.githubusercontent.com/39655003/181219444-dac390a4-9d56-4b58-8040-edf9a2aa2dda.jpg)
